### ISSUE TITLE
Support for Windows 

### ISSUE THREAD

**Issue by edosssa** [simov/native-messaging#5]
The messaging host file uses a shebang which is not supported on windows. How do I get this working on windows?

**Comment by ghost** [comment]
According to some answers on StackOverflow (https://stackoverflow.com/questions/33509816/what-exactly-does-usr-bin-env-node-do-at-the-beginning-of-node-files), Windows ignores the shebang line, and uses the default program depending on the type of file. So I ended up doing 'example.js' --> right click -- > properties --> opens with --> node.exe. And it worked.

**Comment by edosssa** [comment]
@Sentero-esp12 you’re right about the ahebang having no effect on Windows. But it turns out the problem was in my build step. I was using parcel to bundle the code. Parcel apparently gets confused when bundling a file with a shebang. It seems to mistake the shebang for a javascript literal and as a result fails to bundle it 🤷🏽‍♂️
