### ISSUE TITLE
Is there a way to detect in the node process that the extension has been disabled/uninstalled? 

### ISSUE THREAD

**Issue by ghost** [simov/native-messaging#6]
When I'm using only a node process and reload the chrome extension, it also reloads (so there is still only 1 node process after each extension reload).
But when I try to spawn a python process from the node process, this node process isn't reloaded alongside the extension and continues to exist, which results in many node and python processes in Task Manager. Deleting the node process manually removes a python process attached to it.
Is there a way to detect in the node file that the extension has been uninstalled/disabled?

**Comment by simov** [comment]
One way is to notify the node process when extension is being reloaded or disabled, if there is an event for that in the Browser Extensions API.

If not then you can poll from the node process, and act appropriately, if lets say, browser isn't responding after 3 hearthbeat signals.

**Comment by ghost** [comment]
Thanks! Polling works for me

Also some info I've found:
Chrome doesn't seem to have an onDisabled/onUninstalled event from within the extension itself (it's only possible to listen to that event from other extensions [when the extension's id is provided]).
Somebody says Chrome sends -1 to the host process when the extension quits:
https://stackoverflow.com/questions/55079220/close-native-host-when-chrome-is-closed-by-the-user but I wasn't able to implement it.
